const Map<String, String> globalNames = {
  'A': 'Agilent Technologies, Inc.',
  'AAL': 'American Airlines Group, Inc.',
  'AAPL': 'Apple Inc.',
  'ABBV': 'AbbVie Inc.',
  'ABNB': 'Airbnb, Inc.',
  'ABT': 'Abbott Laboratories',
  'ACGL': 'Arch Capital Group Ltd.',
  'ACN': 'Accenture plc',
  'ADBE': 'Adobe Inc.',
  'ADI': 'Analog Devices, Inc.',
  'ADM': 'Archer-Daniels-Midland Company',
  'ADP': 'Automatic Data Processing, Inc.',
  'ADSK': 'Autodesk, Inc.',
  'AEE': 'Ameren Corporation',
  'AEP': 'American Electric Power Company',
  'AES': 'The AES Corporation',
  'AFL': 'AFLAC Incorporated',
  'AFRM': 'Affirm Holdings, Inc.',
  'AI': 'C3.ai, Inc.',
  'AIG': 'American International Group, I',
  'AIZ': 'Assurant, Inc.',
  'AJG': 'Arthur J. Gallagher & Co.',
  'AKAM': 'Akamai Technologies, Inc.',
  'AKRO': 'AKRO',
  'ALB': 'Albemarle Corporation',
  'ALGN': 'Align Technology, Inc.',
  'ALKS': 'Alkermes plc',
  'ALL': 'Allstate Corporation (The)',
  'ALLE': 'Allegion plc',
  'AMAT': 'Applied Materials, Inc.',
  'AMCR': 'Amcor plc',
  'AMD': 'Advanced Micro Devices, Inc.',
  'AME': 'AMETEK, Inc.',
  'AMGN': 'Amgen Inc.',
  'AMKR': 'Amkor Technology, Inc.',
  'AMP': 'Ameriprise Financial, Inc.',
  'AMT': 'American Tower Corporation (REI',
  'AMZN': 'Amazon.com, Inc.',
  'ANET': 'Arista Networks, Inc.',
  'ANSS': 'ANSS',
  'AON': 'Aon plc',
  'AOS': 'A.O. Smith Corporation',
  'APA': 'APA Corporation',
  'APD': 'Air Products and Chemicals, Inc',
  'APH': 'Amphenol Corporation',
  'APP': 'Applovin Corporation',
  'APTV': 'Aptiv PLC',
  'ARCC': 'Ares Capital Corporation',
  'ARE': 'Alexandria Real Estate Equities',
  'ARM': 'Arm Holdings plc',
  'ARRY': 'Array Technologies, Inc.',
  'ASML': 'ASML Holding N.V. - New York Re',
  'ASND': 'Ascendis Pharma A/S',
  'ASTS': 'AST SpaceMobile, Inc.',
  'ATO': 'Atmos Energy Corporation',
  'AVB': 'AvalonBay Communities, Inc.',
  'AVGO': 'Broadcom Inc.',
  'AVY': 'Avery Dennison Corporation',
  'AWK': 'American Water Works Company, I',
  'AXON': 'Axon Enterprise, Inc.',
  'AXP': 'American Express Company',
  'AZN': 'AstraZeneca PLC',
  'AZO': 'AutoZone, Inc.',
  'BA': 'Boeing Company (The)',
  'BAC': 'Bank of America Corporation',
  'BALL': 'Ball Corporation',
  'BAX': 'Baxter International Inc.',
  'BBWI': 'Bath & Body Works, Inc.',
  'BBY': 'Best Buy Co., Inc.',
  'BDX': 'Becton, Dickinson and Company',
  'BEAM': 'Beam Therapeutics Inc.',
  'BEKE': 'KE Holdings Inc',
  'BEN': 'Franklin Resources, Inc.',
  'BF.B': 'BF.B May 2026 37.500 call',
  'BG': 'Bunge Limited',
  'BIDU': 'Baidu, Inc.',
  'BIIB': 'Biogen Inc.',
  'BILI': 'Bilibili Inc.',
  'BITF': 'BitFuFu Inc.',
  'BK': 'The Bank of New York Mellon Cor',
  'BKNG': 'Booking Holdings Inc. Common St',
  'BKR': 'Baker Hughes Company',
  'BLDR': 'Builders FirstSource, Inc.',
  'BLK': 'BlackRock, Inc.',
  'BLOCK': 'Block, Inc.',
  'BMBL': 'Bumble Inc.',
  'BMRN': 'BioMarin Pharmaceutical Inc.',
  'BMY': 'Bristol-Myers Squibb Company',
  'BR': 'Broadridge Financial Solutions,',
  'BRK.B': 'YieldMax BRK.B Option Income St',
  'BRO': 'Brown & Brown, Inc.',
  'BSX': 'Boston Scientific Corporation',
  'BTDR': 'Bitdeer Technologies Group',
  'BWA': 'BorgWarner Inc.',
  'BX': 'Blackstone Inc.',
  'BXP': 'BXP, Inc.',
  'C': 'Citigroup, Inc.',
  'CAG': 'ConAgra Brands, Inc.',
  'CAH': 'Cardinal Health, Inc.',
  'CAN': 'Canaan Inc.',
  'CARR': 'Carrier Global Corporation',
  'CAT': 'Caterpillar, Inc.',
  'CB': 'Chubb Limited',
  'CBOE': 'Cboe Global Markets, Inc.',
  'CBRE': 'CBRE Group Inc',
  'CCEP': 'Coca-Cola Europacific Partners ',
  'CCI': 'Crown Castle Inc.',
  'CCL': 'Carnival Corporation Ltd.',
  'CDNS': 'Cadence Design Systems, Inc.',
  'CDW': 'CDW Corporation',
  'CE': 'Celanese Corporation',
  'CEG': 'Constellation Energy Corporatio',
  'CF': 'CF Industries Holdings, Inc.',
  'CFG': 'Citizens Financial Group, Inc.',
  'CFLT': 'CFLT',
  'CG': 'The Carlyle Group Inc.',
  'CHD': 'Church & Dwight Company, Inc.',
  'CHKP': 'Check Point Software Technologi',
  'CHRW': 'C.H. Robinson Worldwide, Inc.',
  'CHTR': 'Charter Communications, Inc.',
  'CI': 'The Cigna Group',
  'CIFR': 'Cipher Digital Inc.',
  'CINF': 'Cincinnati Financial Corporatio',
  'CL': 'Colgate-Palmolive Company',
  'CLSK': 'CleanSpark, Inc.',
  'CLX': 'Clorox Company (The)',
  'CMCSA': 'Comcast Corporation',
  'CME': 'CME Group Inc.',
  'CMG': 'Chipotle Mexican Grill, Inc.',
  'CMI': 'Cummins Inc.',
  'CMS': 'CMS Energy Corporation',
  'CNC': 'Centene Corporation',
  'CNP': 'CenterPoint Energy, Inc (Holdin',
  'COF': 'Capital One Financial Corporati',
  'COHR': 'Coherent Corp.',
  'COIN': 'Coinbase Global, Inc.',
  'COO': 'The Cooper Companies, Inc.',
  'COP': 'ConocoPhillips',
  'COR': 'Cencora, Inc.',
  'COST': 'Costco Wholesale Corporation',
  'CPAY': 'Corpay, Inc.',
  'CPB': 'The Campbell\'s Company',
  'CPRT': 'Copart, Inc.',
  'CPT': 'Camden Property Trust',
  'CRL': 'Charles River Laboratories Inte',
  'CRM': 'Salesforce, Inc.',
  'CROX': 'Crocs, Inc.',
  'CRSP': 'CRISPR Therapeutics AG',
  'CRWD': 'CrowdStrike Holdings, Inc.',
  'CSCO': 'Cisco Systems, Inc.',
  'CSGP': 'CoStar Group, Inc.',
  'CSIQ': 'Canadian Solar Inc.',
  'CSX': 'CSX Corporation',
  'CTAS': 'Cintas Corporation',
  'CTRA': 'Ciputra Development Tbk',
  'CTSH': 'Cognizant Technology Solutions ',
  'CTVA': 'Corteva, Inc.',
  'CVS': 'CVS Health Corporation',
  'CVX': 'Chevron Corporation',
  'CYBR': 'EVOLVE CYBER SECURITY INDEX UH ',
  'CZR': 'Caesars Entertainment, Inc.',
  'D': 'Dominion Energy, Inc.',
  'DAL': 'Delta Air Lines, Inc.',
  'DAY': 'Brent Crude Oil Last Day Financ',
  'DD': 'DuPont de Nemours, Inc.',
  'DDOG': 'Datadog, Inc.',
  'DE': 'Deere & Company',
  'DECK': 'Deckers Outdoor Corporation',
  'DELL': 'Dell Technologies Inc.',
  'DFS': 'KAVVERI DFS & WIR TEC LTD',
  'DG': 'Dollar General Corporation',
  'DGX': 'Quest Diagnostics Incorporated',
  'DHI': 'D.R. Horton, Inc.',
  'DHR': 'Danaher Corporation',
  'DIS': 'Walt Disney Company (The)',
  'DKNG': 'DraftKings Inc.',
  'DLR': 'Digital Realty Trust, Inc.',
  'DLTR': 'Dollar Tree, Inc.',
  'DNA': 'Ginkgo Bioworks Holdings, Inc.',
  'DOC': 'Healthpeak Properties, Inc.',
  'DOCN': 'DigitalOcean Holdings, Inc.',
  'DOCS': 'Doximity, Inc.',
  'DOCU': 'DocuSign, Inc.',
  'DOV': 'Dover Corporation',
  'DOW': 'Dow Inc.',
  'DPZ': 'Domino\'s Pizza Inc',
  'DRI': 'Darden Restaurants, Inc.',
  'DTE': 'DTE Energy Company',
  'DUK': 'Duke Energy Corporation (Holdin',
  'DUOL': 'Duolingo, Inc.',
  'DVA': 'DaVita Inc.',
  'DVN': 'Devon Energy Corporation',
  'DXCM': 'DexCom, Inc.',
  'EA': 'Electronic Arts Inc.',
  'EBAY': 'eBay Inc.',
  'ECL': 'Ecolab Inc.',
  'ED': 'Consolidated Edison, Inc.',
  'EDIT': 'Editas Medicine, Inc.',
  'EFX': 'Equifax, Inc.',
  'EG': 'Everest Group, Ltd.',
  'EIX': 'Edison International',
  'EL': 'Estee Lauder Companies, Inc. (T',
  'ELV': 'Elevance Health, Inc.',
  'EMN': 'Eastman Chemical Company',
  'EMR': 'Emerson Electric Company',
  'ENFN': 'ENFN',
  'ENPH': 'Enphase Energy, Inc.',
  'EOG': 'EOG Resources, Inc.',
  'EPAM': 'EPAM Systems, Inc.',
  'EQIX': 'Equinix, Inc.',
  'EQR': 'Equity Residential',
  'EQT': 'EQT Corporation',
  'ERIC': 'Ericsson',
  'ERIE': 'Erie Indemnity Company',
  'ES': 'Eversource Energy (D/B/A)',
  'ESS': 'Essex Property Trust, Inc.',
  'ESTC': 'Elastic N.V.',
  'ETN': 'Eaton Corporation, PLC',
  'ETR': 'Entergy Corporation',
  'ETSY': 'Etsy, Inc.',
  'EVRG': 'Evergy, Inc.',
  'EW': 'Edwards Lifesciences Corporatio',
  'EXAS': 'EXASOL AG                     N',
  'EXC': 'Exelon Corporation',
  'EXPD': 'Expeditors International of Was',
  'EXPE': 'Expedia Group, Inc.',
  'EXR': 'Extra Space Storage Inc',
  'F': 'Ford Motor Company',
  'FANG': 'Diamondback Energy, Inc.',
  'FAST': 'Fastenal Company',
  'FCNCA': 'First Citizens BancShares, Inc.',
  'FCX': 'Freeport-McMoRan, Inc.',
  'FDS': 'FactSet Research Systems Inc.',
  'FDX': 'FedEx Corporation',
  'FE': 'FirstEnergy Corp.',
  'FFIV': 'F5, Inc.',
  'FI': 'Brent Crude Oil Last Day Financ',
  'FICO': 'Fair Isaac Corporation',
  'FIS': 'Fidelity National Information S',
  'FITB': 'Fifth Third Bancorp',
  'FLEX': 'Flex Ltd.',
  'FMC': 'FMC Corporation',
  'FOX': 'Fox Corporation',
  'FOXA': 'Fox Corporation',
  'FRT': 'Federal Realty Investment Trust',
  'FSLR': 'First Solar, Inc.',
  'FSLY': 'Fastly, Inc.',
  'FTNT': 'Fortinet, Inc.',
  'FTV': 'Fortive Corporation',
  'FUTU': 'Futu Holdings Limited',
  'FVRR': 'Fiverr International Ltd.',
  'GD': 'General Dynamics Corporation',
  'GDDY': 'GoDaddy Inc.',
  'GE': 'GE Aerospace',
  'GEHC': 'GE HealthCare Technologies Inc.',
  'GEN': 'Gen Digital Inc.',
  'GEV': 'GE Vernova Inc.',
  'GFS': 'GlobalFoundries Inc.',
  'GILD': 'Gilead Sciences, Inc.',
  'GIS': 'General Mills, Inc.',
  'GL': 'Globe Life Inc.',
  'GLW': 'Corning Incorporated',
  'GM': 'General Motors Company',
  'GNRC': 'Generac Holdlings Inc.',
  'GOOG': 'Alphabet Inc.',
  'GOOGL': 'Alphabet Inc.',
  'GPC': 'Genuine Parts Company',
  'GPN': 'Global Payments Inc.',
  'GRMN': 'Garmin Ltd.',
  'GS': 'Goldman Sachs Group, Inc. (The)',
  'GTLB': 'GitLab Inc.',
  'GWW': 'W.W. Grainger, Inc.',
  'HAL': 'Halliburton Company',
  'HAS': 'Hasbro, Inc.',
  'HBAN': 'Huntington Bancshares Incorpora',
  'HCA': 'HCA Healthcare, Inc.',
  'HCP': 'Health Care UltraSector ProFund',
  'HD': 'Home Depot, Inc. (The)',
  'HES': 'Hesai Group',
  'HIG': 'The Hartford Insurance Group, I',
  'HII': 'Huntington Ingalls Industries, ',
  'HLT': 'Hilton Worldwide Holdings Inc.',
  'HOLX': 'HOLX',
  'HON': 'Honeywell International Inc.',
  'HOOD': 'Robinhood Markets, Inc.',
  'HPE': 'Hewlett Packard Enterprise Comp',
  'HPQ': 'HP Inc.',
  'HQY': 'HealthEquity, Inc.',
  'HRL': 'Hormel Foods Corporation',
  'HSIC': 'Henry Schein, Inc.',
  'HST': 'Host Hotels & Resorts, Inc.',
  'HSY': 'The Hershey Company',
  'HUBB': 'Hubbell Inc',
  'HUM': 'Humana Inc.',
  'HUT': 'Hut 8 Corp.',
  'HWM': 'Howmet Aerospace Inc.',
  'IBM': 'International Business Machines',
  'ICE': 'Intercontinental Exchange Inc.',
  'IDXX': 'IDEXX Laboratories, Inc.',
  'IEX': 'IDEX Corporation',
  'IFF': 'International Flavors & Fragran',
  'ILMN': 'Illumina, Inc.',
  'INCY': 'Incyte Corporation',
  'INSM': 'Insmed Incorporated',
  'INTC': 'Intel Corporation',
  'INTU': 'Intuit Inc.',
  'INVH': 'Invitation Homes Inc.',
  'IONQ': 'IonQ, Inc.',
  'IP': 'International Paper Company',
  'IPG': 'IPG Photonics Corporation',
  'IQ': 'iQIYI, Inc.',
  'IQV': 'IQVIA Holdings, Inc.',
  'IR': 'Ingersoll Rand Inc.',
  'IREN': 'IREN LIMITED',
  'IRM': 'Iron Mountain Incorporated (Del',
  'ISRG': 'Intuitive Surgical, Inc.',
  'IT': 'Gartner, Inc.',
  'ITW': 'Illinois Tool Works Inc.',
  'IVZ': 'Invesco Ltd',
  'J': 'Jacobs Solutions Inc.',
  'JAZZ': 'Jazz Pharmaceuticals plc',
  'JBHT': 'J.B. Hunt Transport Services, I',
  'JBL': 'Jabil Inc.',
  'JCI': 'Johnson Controls International ',
  'JD': 'JD.com, Inc.',
  'JKHY': 'Jack Henry & Associates, Inc.',
  'JNJ': 'Johnson & Johnson',
  'JNPR': 'JNPR',
  'JPM': 'JP Morgan Chase & Co.',
  'K': 'USD/KRW',
  'KDP': 'Keurig Dr Pepper Inc.',
  'KEY': 'KeyCorp',
  'KEYS': 'Keysight Technologies Inc.',
  'KHC': 'The Kraft Heinz Company',
  'KIM': 'Kimco Realty Corporation (HC)',
  'KKR': 'KKR & Co. Inc.',
  'KLAC': 'KLA Corporation',
  'KMB': 'Kimberly-Clark Corporation',
  'KMI': 'Kinder Morgan, Inc.',
  'KMX': 'CarMax Inc',
  'KO': 'Coca-Cola Company (The)',
  'KR': 'Kroger Company (The)',
  'KTOS': 'Kratos Defense & Security Solut',
  'KVUE': 'Kenvue Inc.',
  'L': 'Loews Corporation',
  'LAMR': 'Lamar Advertising Company',
  'LCID': 'Lucid Group, Inc.',
  'LDOS': 'Leidos Holdings, Inc.',
  'LEGN': 'Legend Biotech Corporation',
  'LEN': 'Lennar Corporation',
  'LH': 'Labcorp Holdings Inc.',
  'LHX': 'L3Harris Technologies, Inc.',
  'LI': 'Li Auto Inc.',
  'LIN': 'Linde plc',
  'LINE': 'Lineage, Inc.',
  'LKQ': 'LKQ Corporation',
  'LLY': 'Eli Lilly and Company',
  'LMT': 'Lockheed Martin Corporation',
  'LNT': 'Alliant Energy Corporation',
  'LOGI': 'Logitech International S.A. - R',
  'LOW': 'Lowe\'s Companies, Inc.',
  'LRCX': 'Lam Research Corporation',
  'LSCC': 'Lattice Semiconductor Corporati',
  'LULU': 'lululemon athletica inc.',
  'LUV': 'Southwest Airlines Company',
  'LVS': 'Las Vegas Sands Corp.',
  'LW': 'Lamb Weston Holdings, Inc.',
  'LYB': 'LyondellBasell Industries NV',
  'LYFT': 'Lyft, Inc.',
  'LYV': 'Live Nation Entertainment, Inc.',
  'MA': 'Mastercard Incorporated',
  'MAA': 'Mid-America Apartment Communiti',
  'MANH': 'Manhattan Associates, Inc.',
  'MAR': 'Marriott International',
  'MARA': 'MARA Holdings, Inc.',
  'MAS': 'Masco Corporation',
  'MCD': 'McDonald\'s Corporation',
  'MCHP': 'Microchip Technology Incorporat',
  'MCK': 'McKesson Corporation',
  'MCO': 'Moody\'s Corporation',
  'MDB': 'MongoDB, Inc.',
  'MDLZ': 'Mondelez International, Inc.',
  'MDT': 'Medtronic plc.',
  'MELI': 'MercadoLibre, Inc.',
  'MET': 'MetLife, Inc.',
  'META': 'Meta Platforms, Inc.',
  'MGM': 'MGM Resorts International',
  'MHK': 'Mohawk Industries, Inc.',
  'MKC': 'McCormick & Company, Incorporat',
  'MKTX': 'MarketAxess Holdings, Inc.',
  'MLM': 'Martin Marietta Materials, Inc.',
  'MMC': 'Micro E-mini S&P MidCap 400 Fut',
  'MMM': '3M Company',
  'MNDY': 'monday.com Ltd.',
  'MNST': 'Monster Beverage Corporation',
  'MO': 'Altria Group, Inc.',
  'MOH': 'Molina Healthcare Inc',
  'MOS': 'Mosaic Company (The)',
  'MPC': 'Marathon Petroleum Corporation',
  'MPWR': 'Monolithic Power Systems, Inc.',
  'MRK': 'Merck & Company, Inc.',
  'MRNA': 'Moderna, Inc.',
  'MRVL': 'Marvell Technology, Inc.',
  'MS': 'Morgan Stanley',
  'MSCI': 'MSCI Inc.',
  'MSFT': 'Microsoft Corporation',
  'MSI': 'Motorola Solutions, Inc.',
  'MTB': 'M&T Bank Corporation',
  'MTCH': 'Match Group, Inc.',
  'MTD': 'Mettler-Toledo International, I',
  'MU': 'Micron Technology, Inc.',
  'MUFG': 'Mitsubishi UFJ Financial Group,',
  'NCLH': 'Norwegian Cruise Line Holdings ',
  'NDAQ': 'Nasdaq, Inc.',
  'NDSN': 'Nordson Corporation',
  'NEE': 'NextEra Energy, Inc.',
  'NEM': 'Newmont Corporation',
  'NET': 'Cloudflare, Inc.',
  'NFLX': 'Netflix, Inc.',
  'NI': 'NiSource Inc',
  'NIO': 'NIO Inc.',
  'NKE': 'Nike, Inc.',
  'NOC': 'Northrop Grumman Corporation',
  'NOK': 'Nokia Corporation Sponsored',
  'NOW': 'ServiceNow, Inc.',
  'NRG': 'NRG Energy, Inc.',
  'NSC': 'Norfolk Southern Corporation',
  'NTAP': 'NetApp, Inc.',
  'NTDOY': 'Nintendo Co., Ltd.',
  'NTES': 'NetEase, Inc.',
  'NTLA': 'Intellia Therapeutics, Inc.',
  'NTRS': 'Northern Trust Corporation',
  'NUE': 'Nucor Corporation',
  'NVDA': 'NVIDIA Corporation',
  'NVR': 'NVR, Inc.',
  'NWS': 'News Corporation',
  'NWSA': 'News Corporation',
  'NXPI': 'NXP Semiconductors N.V.',
  'O': 'Realty Income Corporation',
  'ODFL': 'Old Dominion Freight Line, Inc.',
  'OKE': 'ONEOK, Inc.',
  'OKTA': 'Okta, Inc.',
  'OLED': 'Universal Display Corporation',
  'OMC': 'Omnicom Group Inc.',
  'ON': 'ON Semiconductor Corporation',
  'ONTO': 'Onto Innovation Inc.',
  'OPEN': 'Opendoor Technologies Inc',
  'ORCL': 'Oracle Corporation',
  'ORLY': 'O\'Reilly Automotive, Inc.',
  'OTIS': 'Otis Worldwide Corporation',
  'OXY': 'Occidental Petroleum Corporatio',
  'PACB': 'Pacific Biosciences of Californ',
  'PANW': 'Palo Alto Networks, Inc.',
  'PARA': 'Paramount Gold Nevada Corp.',
  'PATH': 'UiPath, Inc.',
  'PAYC': 'Paycom Software, Inc.',
  'PAYX': 'Paychex, Inc.',
  'PCAR': 'PACCAR Inc.',
  'PCG': 'Pacific Gas & Electric Co.',
  'PCTY': 'Paylocity Holding Corporation',
  'PDD': 'PDD Holdings Inc.',
  'PEG': 'Public Service Enterprise Group',
  'PENN': 'PENN Entertainment, Inc.',
  'PEP': 'Pepsico, Inc.',
  'PFE': 'Pfizer, Inc.',
  'PFG': 'Principal Financial Group Inc',
  'PG': 'Procter & Gamble Company (The)',
  'PGR': 'Progressive Corporation (The)',
  'PH': 'Parker-Hannifin Corporation',
  'PHM': 'PulteGroup, Inc.',
  'PKG': 'Packaging Corporation of Americ',
  'PLD': 'Prologis, Inc.',
  'PLTR': 'Palantir Technologies Inc.',
  'PLUG': 'Plug Power, Inc.',
  'PM': 'Philip Morris International Inc',
  'PNC': 'PNC Financial Services Group, I',
  'PNR': 'Pentair plc.',
  'PNW': 'Pinnacle West Capital Corporati',
  'PODD': 'Insulet Corporation',
  'POOL': 'Pool Corporation',
  'PPG': 'PPG Industries, Inc.',
  'PPL': 'PPL Corporation',
  'PRU': 'Prudential Financial, Inc.',
  'PSA': 'Public Storage',
  'PSX': 'Phillips 66',
  'PTC': 'PTC Inc.',
  'PTON': 'Peloton Interactive, Inc.',
  'PWR': 'Quanta Services, Inc.',
  'PYPL': 'PayPal Holdings, Inc.',
  'QBTS': 'D-Wave Quantum Inc.',
  'QCOM': 'QUALCOMM Incorporated',
  'QDEL': 'QuidelOrtho Corporation',
  'QLYS': 'Qualys, Inc.',
  'QRVO': 'Qorvo, Inc.',
  'RBLX': 'Roblox Corporation',
  'RCL': 'Royal Caribbean Cruises Ltd.',
  'REG': 'Regency Centers Corporation',
  'REGN': 'Regeneron Pharmaceuticals, Inc.',
  'RF': 'Regions Financial Corporation',
  'RGEN': 'Repligen Corporation',
  'RIOT': 'Riot Platforms, Inc.',
  'RIVN': 'Rivian Automotive, Inc.',
  'RJF': 'Raymond James Financial, Inc.',
  'RKLB': 'Rocket Lab Corporation',
  'RL': 'Ralph Lauren Corporation',
  'RMD': 'ResMed Inc.',
  'ROK': 'Rockwell Automation, Inc.',
  'ROKU': 'Roku, Inc.',
  'ROL': 'Rollins, Inc.',
  'ROP': 'Roper Technologies, Inc.',
  'ROST': 'Ross Stores, Inc.',
  'RPD': 'Rapid7, Inc.',
  'RSG': 'Republic Services, Inc.',
  'RTX': 'RTX Corporation',
  'RUN': 'Sunrun Inc.',
  'RVTY': 'Revvity, Inc.',
  'RXRX': 'Recursion Pharmaceuticals, Inc.',
  'S': 'SentinelOne, Inc.',
  'SAIA': 'Saia, Inc.',
  'SAP': 'SAP  SE',
  'SBAC': 'SBA Communications Corporation',
  'SBUX': 'Starbucks Corporation',
  'SCHW': 'Charles Schwab Corporation (The',
  'SEDG': 'SolarEdge Technologies, Inc.',
  'SFM': 'Sprouts Farmers Market, Inc.',
  'SHOP': 'Shopify Inc.',
  'SHW': 'Sherwin-Williams Company (The)',
  'SIRI': 'SiriusXM Holdings Inc.',
  'SJM': 'The J.M. Smucker Company',
  'SLB': 'SLB Limited',
  'SMCI': 'Super Micro Computer, Inc.',
  'SNA': 'Snap-On Incorporated',
  'SNOW': 'Snowflake Inc.',
  'SNPS': 'Synopsys, Inc.',
  'SO': 'Southern Company (The)',
  'SOFI': 'SoFi Technologies, Inc.',
  'SOLV': 'Solventum Corporation',
  'SONY': 'Sony Group Corporation',
  'SOUN': 'SoundHound AI, Inc.',
  'SPCE': 'Virgin Galactic Holdings, Inc.',
  'SPG': 'Simon Property Group, Inc.',
  'SPGI': 'S&P Global Inc.',
  'SPLK': 'SPLK',
  'SPSC': 'SPS Commerce, Inc.',
  'SQ': 'Bristol-Myers Squibb Company',
  'SRE': 'DBA Sempra',
  'SRPT': 'Sarepta Therapeutics, Inc.',
  'STE': 'STERIS plc (Ireland)',
  'STLD': 'Steel Dynamics, Inc.',
  'STM': 'STMicroelectronics N.V.',
  'STNE': 'StoneCo Ltd.',
  'STT': 'State Street Corporation',
  'STX': 'Seagate Technology Holdings PLC',
  'STZ': 'Constellation Brands, Inc.',
  'SW': 'Smurfit WestRock plc',
  'SWK': 'Stanley Black & Decker, Inc.',
  'SWKS': 'Skyworks Solutions, Inc.',
  'SYF': 'Synchrony Financial',
  'SYK': 'Stryker Corporation',
  'SYY': 'Sysco Corporation',
  'T': 'AT&T Inc.',
  'TAP': 'Molson Coors Beverage Company',
  'TCOM': 'Trip.com Group Limited',
  'TDG': 'Transdigm Group Incorporated',
  'TDY': 'Teledyne Technologies Incorpora',
  'TEAM': 'Atlassian Corporation',
  'TECH': 'Bio-Techne Corp',
  'TEL': 'TE Connectivity plc',
  'TENB': 'Tenable Holdings, Inc.',
  'TER': 'Teradyne, Inc.',
  'TFC': 'Truist Financial Corporation',
  'TGT': 'Target Corporation',
  'TJX': 'TJX Companies, Inc. (The)',
  'TME': 'Tencent Music Entertainment Gro',
  'TMO': 'Thermo Fisher Scientific Inc',
  'TMUS': 'T-Mobile US, Inc.',
  'TOST': 'Toast, Inc.',
  'TPG': 'TPG Inc.',
  'TPL': 'Texas Pacific Land Corporation',
  'TPR': 'Tapestry, Inc.',
  'TRGP': 'Targa Resources, Inc.',
  'TRMB': 'Trimble Inc.',
  'TROW': 'T. Rowe Price Group, Inc.',
  'TRV': 'The Travelers Companies, Inc.',
  'TSCO': 'Tractor Supply Company',
  'TSLA': 'Tesla, Inc.',
  'TSM': 'Taiwan Semiconductor Manufactur',
  'TSN': 'Tyson Foods, Inc.',
  'TT': 'Trane Technologies plc',
  'TTD': 'The Trade Desk, Inc.',
  'TTMI': 'TTM Technologies, Inc.',
  'TTWO': 'Take-Two Interactive Software, ',
  'TXN': 'Texas Instruments Incorporated',
  'TXT': 'Textron Inc.',
  'TYL': 'Tyler Technologies, Inc.',
  'U': 'Unity Software Inc.',
  'UAL': 'United Airlines Holdings, Inc.',
  'UBER': 'Uber Technologies, Inc.',
  'UDR': 'UDR, Inc.',
  'UHS': 'Universal Health Services, Inc.',
  'ULTA': 'Ulta Beauty, Inc.',
  'UNH': 'UnitedHealth Group Incorporated',
  'UNP': 'Union Pacific Corporation',
  'UPS': 'United Parcel Service, Inc.',
  'UPST': 'Upstart Holdings, Inc.',
  'URI': 'United Rentals, Inc.',
  'USB': 'U.S. Bancorp',
  'V': 'Visa Inc.',
  'VCTR': 'Victory Capital Holdings, Inc. ',
  'VICI': 'VICI Properties Inc.',
  'VLO': 'Valero Energy Corporation',
  'VLTO': 'Veralto Corp',
  'VMC': 'Vulcan Materials Company (Holdi',
  'VRNS': 'Varonis Systems, Inc.',
  'VRSK': 'Verisk Analytics, Inc.',
  'VRSN': 'VeriSign, Inc.',
  'VRTX': 'Vertex Pharmaceuticals Incorpor',
  'VST': 'Vistra Corp.',
  'VTR': 'Ventas, Inc.',
  'VTRS': 'Viatris Inc.',
  'VZ': 'Verizon Communications Inc.',
  'WAB': 'Westinghouse Air Brake Technolo',
  'WAT': 'Waters Corporation',
  'WB': 'Weibo Corporation',
  'WBA': 'Wild Bunch AG                 I',
  'WBD': 'Warner Bros. Discovery, Inc. - ',
  'WDAY': 'Workday, Inc.',
  'WDC': 'Western Digital Corporation',
  'WEC': 'WEC Energy Group, Inc.',
  'WELL': 'Welltower Inc.',
  'WFC': 'Wells Fargo & Company',
  'WIX': 'Wix.com Ltd.',
  'WM': 'Waste Management, Inc.',
  'WMB': 'Williams Companies, Inc. (The)',
  'WMT': 'Walmart Inc.',
  'WRB': 'W.R. Berkley Corporation',
  'WSM': 'Williams-Sonoma, Inc.',
  'WST': 'West Pharmaceutical Services, I',
  'WTW': 'Willis Towers Watson Public Lim',
  'WULF': 'TeraWulf Inc.',
  'WY': 'Weyerhaeuser Company',
  'WYNN': 'Wynn Resorts, Limited',
  'XEL': 'Xcel Energy Inc.',
  'XMTR': 'Xometry, Inc.',
  'XOM': 'Exxon Mobil Corporation',
  'XPEV': 'XPeng Inc.',
  'XYL': 'Xylem Inc.',
  'YMM': 'Full Truck Alliance Co. Ltd.',
  'YUM': 'Yum! Brands, Inc.',
  'ZBH': 'Zimmer Biomet Holdings, Inc.',
  'ZBRA': 'Zebra Technologies Corporation',
  'ZI': 'ZIM Integrated Shipping Service',
  'ZM': 'Zoom Communications, Inc.',
  'ZS': 'Zscaler, Inc.',
  'ZSAN': 'SANMITRA COMMERCIAL LTD.',
  'ZTS': 'Zoetis Inc.',
};
